### PR TITLE
Overrides module

### LINKED ISSUE #86: overrides for source cause failure
Hi @wata727 

we use overrides (https://www.terraform.io/docs/configuration/override.html) quite extensively - because it suits our CI/CD tooling - but this causes issues for TFlint...

-- main.tf
module "foo" {
  a = "b"
  c = "d"
}

-- main_override.tf
module "foo" {
    source = "git::http://some_git_url.git?ref=master"
}

I get:
ERROR: Invalid module source in foo

Thanks again for the lovely TFlint tool.  We love it.
N

### PR DESCRIPTION
**Pull request by wata727**
Fix #86 

## ToDo
- [x] Introduce `shcema.Module`
- [x] Add test
- [x] Rewrite `terraform_module_pinned_source`

### CODE REVIEW

File: schema/module.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
+package schema
+
+import (
+	"crypto/md5"
```
Comment (wata727) [inline schema/module.go]: __[gometalinter]__
* [gas] Use of weak cryptographic primitive,HIGH,HIGH

Comment (wata727) [inline schema/module.go]: `md5` is not used for encryption.

File: detector/test_helper.go [hunk 2]
```diff
@@ -66,14 +68,29 @@ func TestDetectByCreatorName(creatorMethod string, src string, stateJSON string,
...
+		for _, template := range schema {
+			for _, resource := range template.FindResources(reflect.Indirect(detector).FieldByName("Target").String()) {
+				detect := detector.MethodByName("Detect")
+				detect.Call([]reflect.Value{
+					reflect.ValueOf(resource),
+					reflect.ValueOf(issues),
+				})
+			}
 		}
+	case "module":
```
Comment (wata727) [inline detector/test_helper.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: detector.go:213:7 detector.go:282:7

File: detector/detector.go [hunk 3]
```diff
@@ -202,22 +187,42 @@ func (d *Detector) detect(creatorMethod string, issues *[]*issue.Issue) {
...
+		for _, template := range d.Schema {
+			for _, resource := range template.FindResources(reflect.Indirect(detector).FieldByName("Target").String()) {
+				detect := detector.MethodByName("Detect")
+				detect.Call([]reflect.Value{
+					reflect.ValueOf(resource),
+					reflect.ValueOf(issues),
+				})
+			}
+		}
+	case "module":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: test_helper.go:82:7 detector.go:282:7

File: detector/detector.go [hunk 4]
```diff
@@ -263,17 +268,27 @@ func (d *Detector) evalToStringTokens(t token.Token) ([]token.Token, error) {
...
-	targetResources := 0
-	for _, template := range d.Templates {
-		targetResources += len(template.Node.(*ast.ObjectList).Filter("resource", target).Items)
+	targets := 0
+	switch targetType {
+	case "resource":
+		for _, template := range d.Schema {
+			targets += len(template.FindResources(target))
+		}
+	case "module":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: test_helper.go:82:7 detector.go:213:7

File: detector/test_helper.go [hunk 5]
```diff
@@ -66,14 +68,29 @@ func TestDetectByCreatorName(creatorMethod string, src string, stateJSON string,
...
 	}
-	for _, template := range schema {
-		for _, resource := range template.Find("resource", reflect.Indirect(detector).FieldByName("Target").String()) {
-			detect := detector.MethodByName("Detect")
-			detect.Call([]reflect.Value{
-				reflect.ValueOf(resource),
-				reflect.ValueOf(issues),
-			})
+	switch reflect.Indirect(detector).FieldByName("TargetType").String() {
+	case "resource":
```
Comment (wata727) [inline detector/test_helper.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: detector.go:203:7 detector.go:278:7

File: detector/detector.go [hunk 6]
```diff
@@ -202,22 +187,42 @@ func (d *Detector) detect(creatorMethod string, issues *[]*issue.Issue) {
...
 
-	for _, template := range d.Schema {
-		for _, resource := range template.Find("resource", reflect.Indirect(detector).FieldByName("Target").String()) {
-			detect := detector.MethodByName("Detect")
-			detect.Call([]reflect.Value{
-				reflect.ValueOf(resource),
-				reflect.ValueOf(issues),
-			})
+	switch reflect.Indirect(detector).FieldByName("TargetType").String() {
+	case "resource":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: test_helper.go:72:7 detector.go:278:7

File: detector/detector.go [hunk 7]
```diff
@@ -263,17 +268,27 @@ func (d *Detector) evalToStringTokens(t token.Token) ([]token.Token, error) {
...
 	if deepCheck && !d.Config.DeepCheck {
 		return true
 	}
 
-	targetResources := 0
-	for _, template := range d.Templates {
-		targetResources += len(template.Node.(*ast.ObjectList).Filter("resource", target).Items)
+	targets := 0
+	switch targetType {
+	case "resource":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: test_helper.go:72:7 detector.go:203:7

File: detector/detector.go [hunk 8]
```diff
@@ -202,22 +136,42 @@ func (d *Detector) detect(creatorMethod string, issues *[]*issue.Issue) {
...
 
-	for _, template := range d.Schema {
-		for _, resource := range template.Find("resource", reflect.Indirect(detector).FieldByName("Target").String()) {
-			detect := detector.MethodByName("Detect")
-			detect.Call([]reflect.Value{
-				reflect.ValueOf(resource),
-				reflect.ValueOf(issues),
-			})
+	switch reflect.Indirect(detector).FieldByName("TargetType").String() {
+	case "resource":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: detector.go:227:7 test_helper.go:71:7

File: detector/detector.go [hunk 9]
```diff
@@ -263,17 +217,27 @@ func (d *Detector) evalToStringTokens(t token.Token) ([]token.Token, error) {
...
 	if deepCheck && !d.Config.DeepCheck {
 		return true
 	}
 
-	targetResources := 0
-	for _, template := range d.Templates {
-		targetResources += len(template.Node.(*ast.ObjectList).Filter("resource", target).Items)
+	targets := 0
+	switch targetType {
+	case "resource":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: detector.go:152:7 test_helper.go:71:7

File: detector/test_helper.go [hunk 10]
```diff
@@ -66,14 +67,29 @@ func TestDetectByCreatorName(creatorMethod string, src string, stateJSON string,
...
```
Comment (wata727) [inline detector/test_helper.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "resource" found in: detector.go:152:7 detector.go:227:7

File: detector/detector.go [hunk 11]
```diff
@@ -202,22 +136,42 @@ func (d *Detector) detect(creatorMethod string, issues *[]*issue.Issue) {
...
+		for _, template := range d.Schema {
+			for _, resource := range template.FindResources(reflect.Indirect(detector).FieldByName("Target").String()) {
+				detect := detector.MethodByName("Detect")
+				detect.Call([]reflect.Value{
+					reflect.ValueOf(resource),
+					reflect.ValueOf(issues),
+				})
+			}
+		}
+	case "module":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: detector.go:231:7 test_helper.go:81:7

File: detector/detector.go [hunk 12]
```diff
@@ -263,17 +217,27 @@ func (d *Detector) evalToStringTokens(t token.Token) ([]token.Token, error) {
...
-	targetResources := 0
-	for _, template := range d.Templates {
-		targetResources += len(template.Node.(*ast.ObjectList).Filter("resource", target).Items)
+	targets := 0
+	switch targetType {
+	case "resource":
+		for _, template := range d.Schema {
+			targets += len(template.FindResources(target))
+		}
+	case "module":
```
Comment (wata727) [inline detector/detector.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: detector.go:162:7 test_helper.go:81:7

File: detector/test_helper.go [hunk 13]
```diff
@@ -66,14 +67,29 @@ func TestDetectByCreatorName(creatorMethod string, src string, stateJSON string,
...
+		for _, template := range schema {
+			for _, resource := range template.FindResources(reflect.Indirect(detector).FieldByName("Target").String()) {
+				detect := detector.MethodByName("Detect")
+				detect.Call([]reflect.Value{
+					reflect.ValueOf(resource),
+					reflect.ValueOf(issues),
+				})
+			}
 		}
+	case "module":
```
Comment (wata727) [inline detector/test_helper.go]: __[gometalinter]__
* [goconst] 2 other occurrence(s) of "module" found in: detector.go:162:7 detector.go:231:7
